DELETE http://localhost:3003/api/blogs/69261dbaa9cd8265d4541ebf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJvb3RlIiwiaWQiOiI2OTI2MmRhYTE3MzM4ZjZkYjc0NTkyNjQiLCJpYXQiOjE3NjQyODA5NzEsImV4cCI6MTc2NDI4NDU3MX0.VLZVO3uHe08QuTSCZUnna1tNlSyoT7jUArn5acgrvGM