PUT http://localhost:3003/api/blogs/68cefdd5a214b74235a72de1
Content-Type: application/json

{
    "title": "Jorge Magnifico",
    "author": "Jorges Bens",
    "url": "http://www.naji.com",
    "likes": 7
}
