PUT http://localhost:3003/api/blogs/690103b05e423ea7c16bc881
Content-Type: application/json

{
    "title": "Jorge Magnifico",
    "author": "Jorges Bens",
    "url": "http://www.naji.com",
    "likes": 7
}
